# Preproducción: como producción pero sin SSL propio, detrás de un proxy.
logging.level.org.themarioga=debug
logging.level.org.hibernate.SQL=info
logging.level.org.hibernate.SQL_SLOW=info
logging.level.org.hibernate.orm.jdbc.bind=warn
logging.level.org.springframework=info
logging.level.root=info
