-- v1.0.0_2 - Catálogo de idiomas y textos i18n
--
-- Todo texto que ve el usuario sale de esta tabla: un literal en el código hace fallar un test.
--
-- Tres bloques:
--   1. Textos comunes traídos tal cual del catálogo de CAH-Telegram (mismo nombre y mismo texto):
--      interfaz, alta de usuario, lobby y errores del motor común. Se duplican en esta base de
--      datos porque los dos despliegues tienen la suya (decisión D1 del plan).
--   2. Errores propios de Secret Hitler, uno por valor de SHErrorEnum. El nombre del tag es
--      "ERROR_" + el nombre del enum: es la convención que aplica ErrorMessageResolver.
--   3. Los textos del juego (SH_*): roles, tablero, votación, sesión legislativa, poderes y finales.
--
-- Cuidado con dos cosas al añadir textos: los \n del SQL se convierten en saltos de línea reales al
-- cargar, y el caché de I18NService se llena en el arranque, así que tocar esta tabla en caliente no
-- se ve hasta reiniciar.

INSERT INTO lang (id, name) VALUES ('es', 'Español'), ('en', 'English');

INSERT INTO tag (tag, lang_id, text) VALUES
    ('ACCEPT', 'es', 'Aceptar'),
    ('ALL_MESSAGES_SENT', 'es', 'Se han enviado todos los mensajes.'),
    ('CANCEL', 'es', 'Cancelar'),
    ('ERROR_COMMAND_SHOULD_BE_ON_GROUP', 'es', 'Este comando debe ser enviado en un grupo en el que esté el bot.'),
    ('ERROR_COMMAND_SHOULD_BE_ON_PRIVATE', 'es', 'Este comando debe ser enviado por privado al bot.'),
    ('ERROR_GAME_ALREADY_CONFIGURED', 'es', 'La partida ya está configurada.'),
    ('ERROR_GAME_ALREADY_EXISTS', 'es', 'Ya hay una partida en este grupo.'),
    ('ERROR_GAME_ALREADY_FILLED', 'es', 'Ya se ha superado el número máximo de jugadores.'),
    ('ERROR_GAME_ALREADY_STARTED', 'es', 'La partida ya está iniciada.'),
    ('ERROR_GAME_CREATOR_ALREADY_EXISTS', 'es', 'Ya tienes una partida abierta en otro grupo.'),
    ('ERROR_GAME_CREATOR_CANNOT_LEAVE', 'es', 'Has creado la partida: no puedes salirte, pero sí borrarla.'),
    ('ERROR_GAME_NOT_CONFIGURED', 'es', 'La partida todavía no está configurada.'),
    ('ERROR_GAME_NOT_ENDING', 'es', 'La partida todavía no ha terminado.'),
    ('ERROR_GAME_NOT_FILLED', 'es', 'La partida aún no ha llegado al número mínimo de jugadores.'),
    ('ERROR_GAME_NOT_FOUND', 'es', 'No hay ninguna partida en este grupo.'),
    ('ERROR_GAME_NOT_STARTED', 'es', 'La partida aun no se ha iniciado.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_PERFORM_ACTION', 'es', 'Solo quien creó la partida puede hacer eso.'),
    ('ERROR_LAW_NOT_FOUND', 'es', 'Esa ley ya no está disponible.'),
    ('ERROR_MESSAGE_TOO_LONG', 'es', 'El mensaje está vacío o es demasiado largo: no se ha enviado a nadie.'),
    ('ERROR_PLAYER_ALREADY_DEAD', 'es', 'Ese jugador está muerto.'),
    ('ERROR_PLAYER_ALREADY_EXISTS', 'es', 'Ya estás en esta partida.'),
    ('ERROR_PLAYER_ALREADY_VOTED', 'es', 'Ya has votado en esta ronda.'),
    ('ERROR_PLAYER_ALREADY_VOTED_DELETION', 'es', 'Ya has votado para borrar esta partida.'),
    ('ERROR_PLAYER_CANNOT_BE_ELECTED', 'es', 'Ese jugador no puede ser elegido.'),
    ('ERROR_PLAYER_CANNOT_BE_INVESTIGATED', 'es', 'Ese jugador no puede ser investigado.'),
    ('ERROR_PLAYER_CANNOT_BE_KILLED', 'es', 'Ese jugador no puede ser ejecutado.'),
    ('ERROR_PLAYER_CANNOT_PERFORM_ACTION', 'es', 'No te toca a ti.'),
    ('ERROR_PLAYER_CANNOT_VOTE_DELETION', 'es', 'No puedes votar para borrar esta partida.'),
    ('ERROR_PLAYER_NOT_FOUND', 'es', 'No estás en esta partida.'),
    ('ERROR_PLAYER_NOT_VALID_CHANCELLOR_CANDIDATE', 'es', 'Ese jugador no puede ser canciller en esta ronda.'),
    ('ERROR_PLAYER_NO_GAMES', 'es', 'No tienes ninguna partida activa.'),
    ('ERROR_ROOM_ALREADY_EXISTS', 'es', 'Ya existe una sala para este grupo.'),
    ('ERROR_ROOM_NOT_ACTIVE', 'es', 'Este grupo está desactivado.'),
    ('ERROR_ROOM_NOT_FOUND', 'es', 'No hay ninguna sala para este grupo.'),
    ('ERROR_ROUND_NOT_ENDING', 'es', 'La ronda todavía no ha terminado.'),
    ('ERROR_ROUND_NOT_FOUND', 'es', 'Esta ronda ya no está en juego.'),
    ('ERROR_ROUND_NOT_STARTED', 'es', 'La ronda todavía no ha empezado.'),
    ('ERROR_ROUND_WRONG_STATUS', 'es', 'Esa acción no toca ahora mismo en esta ronda.'),
    ('ERROR_SELECTION_INVALID', 'es', 'No he encontrado eso. Contesta con el número que aparece a la izquierda en la lista.'),
    ('ERROR_USER_ALREADY_EXISTS', 'es', 'Ya estás registrado.'),
    ('ERROR_USER_NOT_ACTIVE', 'es', 'Tu usuario está desactivado. Escríbeme /start por privado.'),
    ('ERROR_USER_NOT_FOUND', 'es', 'El usuario no existe.'),
    ('ERROR_USER_NOT_REGISTERED', 'es', 'Antes de jugar tienes que escribirme /start por privado.'),
    ('ERROR_VETO_NOT_ACTIVE', 'es', 'El poder de veto todavía no está desbloqueado.'),
    ('GAME_CHANGE_MAX_N_PLAYERS', 'es', 'Cambiar nº máximo de jugadores'),
    ('GAME_CONFIGURE_BUTTON', 'es', 'Configurar la partida'),
    ('GAME_CREATED_CURRENT_PLAYER_NUMBER', 'es', 'Se han unido estos <b>{0}</b> jugadores:'),
    ('GAME_CREATED_CURRENT_VOTE_DELETION_NUMBER', 'es', '<b>{0}</b> jugador/es han votado borrar la partida.'),
    ('GAME_CREATED_GROUP', 'es', '¡Ya he creado la partida!'),
    ('GAME_CREATING', 'es', 'Un momentito, estoy creando la partida...'),
    ('GAME_DELETED', 'es', 'Se ha borrado la partida.'),
    ('GAME_DELETE_BUTTON', 'es', 'Borrar partida'),
    ('GAME_DELETION_ALL', 'es', 'Se han borrado todas las partidas.'),
    ('GAME_DELETION_FORCED', 'es', 'Lo sentimos. Su partida ha sido borrada por la administración. Puede crear una partida nueva.'),
    ('GAME_DELETION_USER', 'es', 'Se ha borrado la partida de {0}.'),
    ('GAME_GLOBAL_MESSAGES_OFF', 'es', 'Mensajes globales desactivados.'),
    ('GAME_GLOBAL_MESSAGES_ON', 'es', 'Mensajes globales activados.'),
    ('GAME_HELP', 'es', '	Bienvenido a la ayuda de {0} versión {1}\n\nPuedes consultar la ayuda en el siguiente enlace: {2}\n\nDisfrutad del bot y... ¡A jugar!\n\nCreado por {3}.'),
    ('GAME_JOIN_BUTTON', 'es', 'Unirse a la partida'),
    ('GAME_LEAVE', 'es', 'Dejar la partida'),
    ('GAME_LEFT', 'es', 'Has dejado la partida'),
    ('GAME_SELECTED_MAX_PLAYER_NUMBER', 'es', 'El número máximo de jugadores es <b>{0}</b>.'),
    ('GAME_SELECT_MAX_PLAYERS', 'es', '\nSelecciona nº máximo de jugadores:'),
    ('GAME_START_BUTTON', 'es', 'Iniciar la partida'),
    ('GO_BACK', 'es', '← Volver'),
    ('NO', 'es', 'No'),
    ('PLAYER_CREATED_GAME', 'es', 'He creado la partida en el grupo, puedes configurarla allí'),
    ('PLAYER_JOINED', 'es', 'Te has unido a la partida.'),
    ('PLAYER_JOINING', 'es', 'Un momentito, estoy intentando unirte a la partida...'),
    ('PLAYER_VOTED_DELETION', 'es', 'Has votado borrar la partida'),
    ('PLAYER_WELCOME', 'es', '¡Bienvenido! Acabo de añadirte a mi base de datos.\nSiempre que necesites ayuda puedes escribir /help\n¡Gracias por unirte!'),
    ('SH_ARGUING', 'es', 'Turno de debate. Cuando queráis, seguid con la ronda siguiente.'),
    ('SH_BOARD', 'es', '<b>Mesa</b>\nLeyes liberales: {0}/{1}\nLeyes fascistas: {2}/{3}\nElecciones fallidas: {4}/3\nJugadores vivos: {5}'),
    ('SH_BOARD_VETO_ENABLED', 'es', 'El veto está desbloqueado.'),
    ('SH_CHANCELLOR_ENACT', 'es', 'El presidente te pasa estas dos leyes. Promulga una:'),
    ('SH_CHANCELLOR_ENACTED', 'es', 'Ley promulgada.'),
    ('SH_CHANCELLOR_ENACTING', 'es', 'El canciller {0} está eligiendo la ley...'),
    ('SH_CHANCELLOR_NOMINATED', 'es', '{0} nomina a {1} como canciller. ¡A votar!'),
    ('SH_ELECTION_TRACKER', 'es', 'Elecciones fallidas seguidas: {0} de 3.'),
    ('SH_GAME_MIN_PLAYERS', 'es', 'Hacen falta al menos {0} jugadores para empezar.'),
    ('SH_GAME_ROLES_REVEALED', 'es', 'Los roles eran:\n{0}'),
    ('SH_KICK_BUTTON', 'es', 'Echar a un jugador'),
    ('SH_KICK_SELECT', 'es', 'Elige a quién echar:'),
    ('SH_LAW_AUTO_ENACTED', 'es', 'Tres elecciones fallidas seguidas: el país se sume en el caos y se promulga la ley de arriba del mazo, que es <b>{0}</b>.'),
    ('SH_LAW_ENACTED', 'es', 'Se promulga una ley <b>{0}</b>.'),
    ('SH_LAW_FASCIST', 'es', 'fascista'),
    ('SH_LAW_LIBERAL', 'es', 'liberal'),
    ('SH_NEXT_ROUND_BUTTON', 'es', 'Siguiente ronda'),
    ('SH_PARTY_FASCIST', 'es', 'fascista'),
    ('SH_PARTY_LIBERAL', 'es', 'liberal'),
    ('SH_PLAYER_DEAD_MARK', 'es', '☠'),
    ('SH_PLAYER_KICKED', 'es', 'Te han echado de la partida.'),
    ('SH_PLAYER_ROLE_LINE', 'es', '{0} — {1}'),
    ('SH_POWER_EXECUTION_ANNOUNCE', 'es', 'El presidente {0} ejecuta a {1}.'),
    ('SH_POWER_EXECUTION_BUTTON', 'es', 'Ejecutar'),
    ('SH_POWER_EXECUTION_SELECT', 'es', 'Elige a quién ejecutar:'),
    ('SH_POWER_INVESTIGATE_ANNOUNCE', 'es', 'El presidente {0} investiga la lealtad de {1}.'),
    ('SH_POWER_INVESTIGATE_BUTTON', 'es', 'Investigar lealtad'),
    ('SH_POWER_INVESTIGATE_RESULT', 'es', '{0} pertenece al partido <b>{1}</b>.'),
    ('SH_POWER_INVESTIGATE_SELECT', 'es', 'Elige a quién investigar:'),
    ('SH_POWER_PEEK_ANNOUNCE', 'es', 'El presidente {0} espía las tres próximas leyes del mazo.'),
    ('SH_POWER_PEEK_BUTTON', 'es', 'Espiar el mazo'),
    ('SH_POWER_PEEK_CONFIRM', 'es', 'Puedes espiar las tres próximas leyes del mazo. Solo las verás tú.'),
    ('SH_POWER_PEEK_RESULT', 'es', 'Las tres próximas leyes del mazo son: {0}.'),
    ('SH_POWER_SELECT', 'es', 'Tienes más de un poder disponible. Elige:'),
    ('SH_POWER_SPECIAL_ELECTION_ANNOUNCE', 'es', 'El presidente {0} convoca una elección especial: {1} será presidente en la próxima ronda.'),
    ('SH_POWER_SPECIAL_ELECTION_BUTTON', 'es', 'Elección especial'),
    ('SH_POWER_SPECIAL_ELECTION_SELECT', 'es', 'Elige al próximo presidente:'),
    ('SH_PRESIDENT_DISCARD', 'es', 'Estas son las tres leyes. Descarta una:'),
    ('SH_PRESIDENT_DISCARDED', 'es', 'Ley descartada. Ahora decide el canciller.'),
    ('SH_PRESIDENT_DISCARDING', 'es', 'El presidente {0} está descartando una ley...'),
    ('SH_PRESIDENT_SELECTING_CHANCELLOR', 'es', '{0} está eligiendo canciller...'),
    ('SH_PRESIDENT_SELECT_CHANCELLOR', 'es', 'Elige a tu canciller:'),
    ('SH_PRESIDENT_USING_POWER', 'es', 'El presidente {0} tiene un poder ejecutivo que usar...'),
    ('SH_ROLE_FASCIST', 'es', 'Eres <b>fascista</b>.\nGanas si se promulgan {0} leyes fascistas o si Hitler sale elegido canciller con tres leyes fascistas en la mesa.'),
    ('SH_ROLE_FELLOW_FASCISTS', 'es', 'Tus compañeros fascistas son: {0}'),
    ('SH_ROLE_HITLER', 'es', 'Eres <b>Hitler</b>.\nGanas con los fascistas, pero si te ejecutan ganan los liberales.'),
    ('SH_ROLE_HITLER_IS', 'es', 'Hitler es: {0}'),
    ('SH_ROLE_HITLER_UNKNOWN', 'es', 'Sois demasiados: no sabes quiénes son los fascistas.'),
    ('SH_ROLE_LIBERAL', 'es', 'Eres <b>liberal</b>.\nGanas si se promulgan {0} leyes liberales o si Hitler es ejecutado.'),
    ('SH_ROLE_NAME_FASCIST', 'es', 'Fascista'),
    ('SH_ROLE_NAME_HITLER', 'es', 'Hitler'),
    ('SH_ROLE_NAME_LIBERAL', 'es', 'Liberal'),
    ('SH_ROUND_STARTED', 'es', '<b>Ronda {0}</b>\nPresidente: {1}'),
    ('SH_VETO_ACCEPTED', 'es', 'El presidente acepta el veto: no se promulga ninguna ley y cuenta como gobierno fallido.'),
    ('SH_VETO_ASK_PRESIDENT', 'es', 'El canciller quiere vetar las dos leyes. ¿Aceptas?'),
    ('SH_VETO_BUTTON', 'es', 'Vetar las dos leyes'),
    ('SH_VETO_PROPOSED', 'es', 'El canciller propone vetar las dos leyes; decide el presidente.'),
    ('SH_VETO_REJECTED', 'es', 'El presidente rechaza el veto: el canciller tiene que promulgar una de las dos leyes.'),
    ('SH_VETO_UNLOCKED', 'es', 'Con {0} leyes fascistas en la mesa, el veto queda desbloqueado.'),
    ('SH_VOTE_CAST', 'es', 'Tu voto queda registrado.'),
    ('SH_VOTE_DETAIL', 'es', '{0}: {1}'),
    ('SH_VOTE_JA', 'es', '👍 Ja!'),
    ('SH_VOTE_NEIN', 'es', '👎 Nein!'),
    ('SH_VOTE_PENDING', 'es', 'Han votado {0} de {1} jugadores.'),
    ('SH_VOTE_RESULT_PASSED', 'es', 'El gobierno sale adelante: {0} a favor, {1} en contra.'),
    ('SH_VOTE_RESULT_REJECTED', 'es', 'El gobierno se rechaza: {0} a favor, {1} en contra.'),
    ('SH_WIN_FASCIST_LAWS', 'es', '¡Se han promulgado {0} leyes fascistas! <b>Ganan los fascistas</b>.'),
    ('SH_WIN_HITLER_CHANCELLOR', 'es', '¡Hitler ha sido elegido canciller con tres leyes fascistas en la mesa! <b>Ganan los fascistas</b>.'),
    ('SH_WIN_HITLER_EXECUTED', 'es', '¡Hitler ha sido ejecutado! <b>Ganan los liberales</b>.'),
    ('SH_WIN_LIBERAL_LAWS', 'es', '¡Se han promulgado {0} leyes liberales! <b>Ganan los liberales</b>.'),
    ('UNKNOWN_ERROR', 'es', 'Ha ocurrido un error inesperado.'),
    ('USER_LANG_CHANGE', 'es', 'Elige tu idioma:'),
    ('USER_LANG_CHANGED', 'es', 'Se ha cambiado el idioma.'),
    ('YES', 'es', 'Sí'),
    ('ACCEPT', 'en', 'Accept'),
    ('ALL_MESSAGES_SENT', 'en', 'All messages sent.'),
    ('CANCEL', 'en', 'Cancel'),
    ('ERROR_COMMAND_SHOULD_BE_ON_GROUP', 'en', 'This command must be sent in a group in which the bot is.'),
    ('ERROR_COMMAND_SHOULD_BE_ON_PRIVATE', 'en', 'This command must be sent privately to the bot.'),
    ('ERROR_GAME_ALREADY_CONFIGURED', 'en', 'The game is already configured.'),
    ('ERROR_GAME_ALREADY_EXISTS', 'en', 'There is already a game in this group.'),
    ('ERROR_GAME_ALREADY_FILLED', 'en', 'The game has already reached the maximum of players.'),
    ('ERROR_GAME_ALREADY_STARTED', 'en', 'The game has already started.'),
    ('ERROR_GAME_CREATOR_ALREADY_EXISTS', 'en', 'You already have a game open in another group.'),
    ('ERROR_GAME_CREATOR_CANNOT_LEAVE', 'en', 'You created this game: you cannot leave it, but you can delete it.'),
    ('ERROR_GAME_NOT_CONFIGURED', 'en', 'The game is not configured yet.'),
    ('ERROR_GAME_NOT_ENDING', 'en', 'The game has not finished yet.'),
    ('ERROR_GAME_NOT_FILLED', 'en', 'The game has not reached the minimum number of players.'),
    ('ERROR_GAME_NOT_FOUND', 'en', 'There is no game in this group.'),
    ('ERROR_GAME_NOT_STARTED', 'en', 'The game has not started.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_PERFORM_ACTION', 'en', 'Only the player who created the game can do that.'),
    ('ERROR_LAW_NOT_FOUND', 'en', 'That policy is no longer available.'),
    ('ERROR_MESSAGE_TOO_LONG', 'en', 'The message is empty or too long: it has not been sent to anyone.'),
    ('ERROR_PLAYER_ALREADY_DEAD', 'en', 'That player is dead.'),
    ('ERROR_PLAYER_ALREADY_EXISTS', 'en', 'You are already in this game.'),
    ('ERROR_PLAYER_ALREADY_VOTED', 'en', 'You already voted this round.'),
    ('ERROR_PLAYER_ALREADY_VOTED_DELETION', 'en', 'You have already voted to delete this game.'),
    ('ERROR_PLAYER_CANNOT_BE_ELECTED', 'en', 'That player cannot be elected.'),
    ('ERROR_PLAYER_CANNOT_BE_INVESTIGATED', 'en', 'That player cannot be investigated.'),
    ('ERROR_PLAYER_CANNOT_BE_KILLED', 'en', 'That player cannot be executed.'),
    ('ERROR_PLAYER_CANNOT_PERFORM_ACTION', 'en', 'It is not your turn.'),
    ('ERROR_PLAYER_CANNOT_VOTE_DELETION', 'en', 'You cannot vote to delete this game.'),
    ('ERROR_PLAYER_NOT_FOUND', 'en', 'You are not in this game.'),
    ('ERROR_PLAYER_NOT_VALID_CHANCELLOR_CANDIDATE', 'en', 'That player cannot be chancellor this round.'),
    ('ERROR_PLAYER_NO_GAMES', 'en', 'You have no active games.'),
    ('ERROR_ROOM_ALREADY_EXISTS', 'en', 'There is already a room for this group.'),
    ('ERROR_ROOM_NOT_ACTIVE', 'en', 'This group is disabled.'),
    ('ERROR_ROOM_NOT_FOUND', 'en', 'There is no room for this group.'),
    ('ERROR_ROUND_NOT_ENDING', 'en', 'The round has not finished yet.'),
    ('ERROR_ROUND_NOT_FOUND', 'en', 'This round is no longer in play.'),
    ('ERROR_ROUND_NOT_STARTED', 'en', 'The round has not started yet.'),
    ('ERROR_ROUND_WRONG_STATUS', 'en', 'That action does not apply to this round right now.'),
    ('ERROR_SELECTION_INVALID', 'en', 'I could not find that. Reply with the number shown on the left of the list.'),
    ('ERROR_USER_ALREADY_EXISTS', 'en', 'You are already registered.'),
    ('ERROR_USER_NOT_ACTIVE', 'en', 'Your user is disabled. Send me /start in a private chat.'),
    ('ERROR_USER_NOT_FOUND', 'en', 'That user does not exist.'),
    ('ERROR_USER_NOT_REGISTERED', 'en', 'Before playing you have to send me /start in a private chat.'),
    ('ERROR_VETO_NOT_ACTIVE', 'en', 'The veto power is not unlocked yet.'),
    ('GAME_CHANGE_MAX_N_PLAYERS', 'en', 'Change number of max players.'),
    ('GAME_CONFIGURE_BUTTON', 'en', 'Configure game'),
    ('GAME_CREATED_CURRENT_PLAYER_NUMBER', 'en', '<b>{0}</b> players have joined:'),
    ('GAME_CREATED_CURRENT_VOTE_DELETION_NUMBER', 'en', '<b>{0}</b> player/s have voted to delete the game.'),
    ('GAME_CREATED_GROUP', 'en', 'I already created the game!'),
    ('GAME_CREATING', 'en', 'Hold on, I´m creating the game...'),
    ('GAME_DELETED', 'en', 'Game deleted.'),
    ('GAME_DELETE_BUTTON', 'en', 'Delete game'),
    ('GAME_DELETION_ALL', 'en', 'All games have been deleted.'),
    ('GAME_DELETION_FORCED', 'en', 'Sorry, the game has been deleted by an admin. You can start a new game.'),
    ('GAME_DELETION_USER', 'en', '{0}´s game has been deleted.'),
    ('GAME_GLOBAL_MESSAGES_OFF', 'en', 'Global messages disabled.'),
    ('GAME_GLOBAL_MESSAGES_ON', 'en', 'Global messages enabled.'),
    ('GAME_HELP', 'en', 'Welcome to the help menu of {0} version {1}\n\nYou can check for help here: {2}\n\nEnjoy the bot and... Let´s play!\n\nMade by {3}.'),
    ('GAME_JOIN_BUTTON', 'en', 'Join game'),
    ('GAME_LEAVE', 'en', 'Leave game'),
    ('GAME_LEFT', 'en', 'You left the game.'),
    ('GAME_SELECTED_MAX_PLAYER_NUMBER', 'en', 'The maximum number of players is <b>{0}</b>.'),
    ('GAME_SELECT_MAX_PLAYERS', 'en', '\nSelect max number of players:'),
    ('GAME_START_BUTTON', 'en', 'Start game'),
    ('GO_BACK', 'en', '← Go back'),
    ('NO', 'en', 'No'),
    ('PLAYER_CREATED_GAME', 'en', 'I created a game in the group, you can configure it there.'),
    ('PLAYER_JOINED', 'en', 'You joined the game.'),
    ('PLAYER_JOINING', 'en', 'Hold on, you are joining the game...'),
    ('PLAYER_VOTED_DELETION', 'en', 'You voted to delete the game.'),
    ('PLAYER_WELCOME', 'en', 'Welcome! I just added you to my database.\nWhen you need help you only have to send me the command /help\nThank you for joining!'),
    ('SH_ARGUING', 'en', 'Time to argue. Move on to the next round whenever you want.'),
    ('SH_BOARD', 'en', '<b>Board</b>\nLiberal policies: {0}/{1}\nFascist policies: {2}/{3}\nFailed elections: {4}/3\nAlive players: {5}'),
    ('SH_BOARD_VETO_ENABLED', 'en', 'The veto power is unlocked.'),
    ('SH_CHANCELLOR_ENACT', 'en', 'The president passes you these two policies. Enact one:'),
    ('SH_CHANCELLOR_ENACTED', 'en', 'Policy enacted.'),
    ('SH_CHANCELLOR_ENACTING', 'en', 'Chancellor {0} is choosing the policy...'),
    ('SH_CHANCELLOR_NOMINATED', 'en', '{0} nominates {1} as chancellor. Time to vote!'),
    ('SH_ELECTION_TRACKER', 'en', 'Failed elections in a row: {0} of 3.'),
    ('SH_GAME_MIN_PLAYERS', 'en', 'At least {0} players are needed to start.'),
    ('SH_GAME_ROLES_REVEALED', 'en', 'The roles were:\n{0}'),
    ('SH_KICK_BUTTON', 'en', 'Kick a player'),
    ('SH_KICK_SELECT', 'en', 'Choose who to kick:'),
    ('SH_LAW_AUTO_ENACTED', 'en', 'Three failed elections in a row: the country falls into chaos and the top policy of the deck is enacted, and it is <b>{0}</b>.'),
    ('SH_LAW_ENACTED', 'en', 'A <b>{0}</b> policy is enacted.'),
    ('SH_LAW_FASCIST', 'en', 'fascist'),
    ('SH_LAW_LIBERAL', 'en', 'liberal'),
    ('SH_NEXT_ROUND_BUTTON', 'en', 'Next round'),
    ('SH_PARTY_FASCIST', 'en', 'fascist'),
    ('SH_PARTY_LIBERAL', 'en', 'liberal'),
    ('SH_PLAYER_DEAD_MARK', 'en', '☠'),
    ('SH_PLAYER_KICKED', 'en', 'You have been kicked from the game.'),
    ('SH_PLAYER_ROLE_LINE', 'en', '{0} — {1}'),
    ('SH_POWER_EXECUTION_ANNOUNCE', 'en', 'President {0} executes {1}.'),
    ('SH_POWER_EXECUTION_BUTTON', 'en', 'Execution'),
    ('SH_POWER_EXECUTION_SELECT', 'en', 'Choose who to execute:'),
    ('SH_POWER_INVESTIGATE_ANNOUNCE', 'en', 'President {0} investigates the loyalty of {1}.'),
    ('SH_POWER_INVESTIGATE_BUTTON', 'en', 'Investigate loyalty'),
    ('SH_POWER_INVESTIGATE_RESULT', 'en', '{0} belongs to the <b>{1}</b> party.'),
    ('SH_POWER_INVESTIGATE_SELECT', 'en', 'Choose who to investigate:'),
    ('SH_POWER_PEEK_ANNOUNCE', 'en', 'President {0} peeks at the next three policies.'),
    ('SH_POWER_PEEK_BUTTON', 'en', 'Policy peek'),
    ('SH_POWER_PEEK_CONFIRM', 'en', 'You can peek at the next three policies in the deck. Only you will see them.'),
    ('SH_POWER_PEEK_RESULT', 'en', 'The next three policies in the deck are: {0}.'),
    ('SH_POWER_SELECT', 'en', 'You have more than one power available. Choose:'),
    ('SH_POWER_SPECIAL_ELECTION_ANNOUNCE', 'en', 'President {0} calls a special election: {1} will be president next round.'),
    ('SH_POWER_SPECIAL_ELECTION_BUTTON', 'en', 'Special election'),
    ('SH_POWER_SPECIAL_ELECTION_SELECT', 'en', 'Choose the next president:'),
    ('SH_PRESIDENT_DISCARD', 'en', 'These are the three policies. Discard one:'),
    ('SH_PRESIDENT_DISCARDED', 'en', 'Policy discarded. Now the chancellor decides.'),
    ('SH_PRESIDENT_DISCARDING', 'en', 'President {0} is discarding a policy...'),
    ('SH_PRESIDENT_SELECTING_CHANCELLOR', 'en', '{0} is choosing a chancellor...'),
    ('SH_PRESIDENT_SELECT_CHANCELLOR', 'en', 'Choose your chancellor:'),
    ('SH_PRESIDENT_USING_POWER', 'en', 'President {0} has an executive power to use...'),
    ('SH_ROLE_FASCIST', 'en', 'You are a <b>fascist</b>.\nYou win if {0} fascist policies are enacted or if Hitler is elected chancellor with three fascist policies on the board.'),
    ('SH_ROLE_FELLOW_FASCISTS', 'en', 'Your fellow fascists are: {0}'),
    ('SH_ROLE_HITLER', 'en', 'You are <b>Hitler</b>.\nYou win with the fascists, but if you are executed the liberals win.'),
    ('SH_ROLE_HITLER_IS', 'en', 'Hitler is: {0}'),
    ('SH_ROLE_HITLER_UNKNOWN', 'en', 'There are too many of you: you do not know who the fascists are.'),
    ('SH_ROLE_LIBERAL', 'en', 'You are a <b>liberal</b>.\nYou win if {0} liberal policies are enacted or if Hitler is executed.'),
    ('SH_ROLE_NAME_FASCIST', 'en', 'Fascist'),
    ('SH_ROLE_NAME_HITLER', 'en', 'Hitler'),
    ('SH_ROLE_NAME_LIBERAL', 'en', 'Liberal'),
    ('SH_ROUND_STARTED', 'en', '<b>Round {0}</b>\nPresident: {1}'),
    ('SH_VETO_ACCEPTED', 'en', 'The president accepts the veto: no policy is enacted and it counts as a failed government.'),
    ('SH_VETO_ASK_PRESIDENT', 'en', 'The chancellor wants to veto both policies. Do you accept?'),
    ('SH_VETO_BUTTON', 'en', 'Veto both policies'),
    ('SH_VETO_PROPOSED', 'en', 'The chancellor proposes to veto both policies; the president decides.'),
    ('SH_VETO_REJECTED', 'en', 'The president rejects the veto: the chancellor must enact one of the two policies.'),
    ('SH_VETO_UNLOCKED', 'en', 'With {0} fascist policies on the board, the veto power is unlocked.'),
    ('SH_VOTE_CAST', 'en', 'Your vote has been registered.'),
    ('SH_VOTE_DETAIL', 'en', '{0}: {1}'),
    ('SH_VOTE_JA', 'en', '👍 Ja!'),
    ('SH_VOTE_NEIN', 'en', '👎 Nein!'),
    ('SH_VOTE_PENDING', 'en', '{0} of {1} players have voted.'),
    ('SH_VOTE_RESULT_PASSED', 'en', 'The government is elected: {0} in favour, {1} against.'),
    ('SH_VOTE_RESULT_REJECTED', 'en', 'The government is rejected: {0} in favour, {1} against.'),
    ('SH_WIN_FASCIST_LAWS', 'en', '{0} fascist policies have been enacted! <b>The fascists win</b>.'),
    ('SH_WIN_HITLER_CHANCELLOR', 'en', 'Hitler has been elected chancellor with three fascist policies on the board! <b>The fascists win</b>.'),
    ('SH_WIN_HITLER_EXECUTED', 'en', 'Hitler has been executed! <b>The liberals win</b>.'),
    ('SH_WIN_LIBERAL_LAWS', 'en', '{0} liberal policies have been enacted! <b>The liberals win</b>.'),
    ('UNKNOWN_ERROR', 'en', 'An unexpected error occurred.'),
    ('USER_LANG_CHANGE', 'en', 'Choose your language:'),
    ('USER_LANG_CHANGED', 'en', 'Language changed successfully.'),
    ('YES', 'en', 'Yes');
