-- v1.0.0_1 - Baseline del esquema (h2)
--
-- Generado desde las entidades con SH-Telegram/src/test/java/.../tools/SchemaGenerator.java,
-- aplicando las naming strategies de Spring Boot 4.1 (SpringImplicitNamingStrategy +
-- PhysicalNamingStrategySnakeCaseImpl). No editar a mano: regenerar si cambia el modelo.
--
-- Base de datos propia, separada de la de CAH-Telegram: las entidades Game, Player y Round de los
-- dos motores tienen el mismo nombre simple y, con la herencia TABLE_PER_CLASS que usan, mapearían
-- a las mismas tablas. Ver la decisión D1 de docs/specs/SH-Telegram-PLAN.md.

    create table game (
        id uuid not null,
        creation_date timestamp(6) not null,
        status tinyint not null check ((status between 0 and 3)),
        creator_id uuid not null unique,
        room_id uuid not null unique,
        failed_votation_counter integer not null,
        last_regular_president_join_order integer,
        max_number_of_players integer not null,
        number_of_fascist_laws_enacted integer not null,
        number_of_liberal_laws_enacted integer not null,
        result varchar(255) check ((result in ('LIBERAL_LAWS','FASCIST_LAWS','HITLER_EXECUTED','HITLER_ELECTED_CHANCELLOR'))),
        veto_is_active boolean not null,
        previous_round_chancellor_id uuid,
        previous_round_president_id uuid,
        special_election_president_id uuid,
        primary key (id)
    );

    create table game_deletion_votes (
        game_id uuid not null,
        user_id uuid not null unique
    );

    create table game_law_discard_deck (
        game_id uuid not null,
        law_id bigint not null unique
    );

    create table game_law_pick_deck (
        game_id uuid not null,
        law_id bigint not null unique
    );

    create table lang (
        id varchar(255) not null,
        name varchar(256) not null unique,
        primary key (id)
    );

    create table law (
        id bigint generated by default as identity,
        type varchar(255) not null check ((type in ('FASCIST','LIBERAL'))),
        primary key (id)
    );

    create table player (
        id uuid not null,
        creation_date timestamp(6) not null,
        join_order integer not null,
        game_id uuid not null,
        user_id uuid not null unique,
        alive boolean not null,
        investigated boolean not null,
        party varchar(255) check ((party in ('LIBERAL','FASCIST'))),
        role varchar(255) check ((role in ('LIBERAL','FASCIST','HITLER'))),
        primary key (id)
    );

    create table room (
        id uuid not null,
        creation_date timestamp(6) not null,
        active boolean not null,
        name varchar(256) not null,
        roomname varchar(128) not null unique,
        primary key (id)
    );

    create table round (
        id uuid not null,
        creation_date timestamp(6) not null,
        round_number integer not null,
        status varchar(255) not null check ((status in ('SELECTING_CHANCELLOR','VOTING_CHANCELLOR','PRESIDENT_DISCARDING_LAW','CHANCELLOR_SELECTING_LAW','DOING_ADDITIONAL_ACTION','ARGUING','ENDING','HITLER_ELECTED_CHANCELLOR','CHANCELLOR_REJECTED','VETO_REQUESTED'))),
        chancellor_id uuid,
        game_id uuid not null unique,
        president_id uuid,
        primary key (id)
    );

    create table round_available_laws (
        round_id uuid not null,
        law_id bigint not null unique
    );

    create table round_votes (
        round_id uuid not null,
        vote varchar(255) not null check ((vote in ('YES','NO'))),
        player_id uuid not null,
        primary key (round_id, player_id)
    );

    create table tag (
        tag varchar(255) not null,
        text varchar(4000) not null,
        lang_id varchar(255) not null,
        primary key (lang_id, tag)
    );

    create table telegram_game (
        board_message_id integer,
        creator_message_id integer not null,
        current_round_message_id integer,
        first_message_id integer not null,
        game_id uuid not null,
        primary key (game_id)
    );

    create table telegram_player (
        action_message_id integer,
        role_message_id integer not null,
        player_id uuid not null,
        primary key (player_id)
    );

    create table telegram_room (
        id bigint not null,
        room_id uuid not null unique,
        primary key (id)
    );

    create table telegram_user (
        id bigint not null,
        language_code varchar(8),
        last_seen timestamp(6),
        user_id uuid not null unique,
        primary key (id)
    );

    create table users (
        id uuid not null,
        creation_date timestamp(6) not null,
        active boolean not null,
        name varchar(256) not null,
        username varchar(64) not null unique,
        lang_id varchar(255) not null,
        primary key (id)
    );

    create index IDX4l8mm4fqoos6fcbx76rvqxer 
       on room (name);

    create index IDX3g1j96g94xpk3lpxl2qbl985x 
       on users (name);

    alter table if exists game 
       add constraint FKgaa020froocdx7nd9ei1tbluq 
       foreign key (previous_round_chancellor_id) 
       references player;

    alter table if exists game 
       add constraint FK3m522mpi951vsqtjkqq99nbjs 
       foreign key (previous_round_president_id) 
       references player;

    alter table if exists game 
       add constraint FKaqt540mda5ntxs7vq4i97hfcj 
       foreign key (special_election_president_id) 
       references player;

    alter table if exists game 
       add constraint FKlg27yqk2n245fmd22auiffyp1 
       foreign key (creator_id) 
       references users;

    alter table if exists game 
       add constraint FKn2dw11xgfbg2agx7v25teb8b 
       foreign key (room_id) 
       references room;

    alter table if exists game_deletion_votes 
       add constraint FKbiuyrsgekoq3ngsposbvt3kax 
       foreign key (user_id) 
       references users;

    alter table if exists game_law_discard_deck 
       add constraint FKnd4r5hq9m1v9jk77lfqmlo1p6 
       foreign key (law_id) 
       references law;

    alter table if exists game_law_discard_deck 
       add constraint FK4qhxc8d4q9y0e00ro49fputp0 
       foreign key (game_id) 
       references game;

    alter table if exists game_law_pick_deck 
       add constraint FKc65u4aoxj0uhlfijxmo7u3a3g 
       foreign key (law_id) 
       references law;

    alter table if exists game_law_pick_deck 
       add constraint FKeghhgomtheio6jcc5i1vdnjmb 
       foreign key (game_id) 
       references game;

    alter table if exists player 
       add constraint FKoycxb69gpaapuv23fn52y0g50 
       foreign key (user_id) 
       references users;

    alter table if exists round 
       add constraint FK5yc5lox8s6oghlh62nc55eoxr 
       foreign key (chancellor_id) 
       references player;

    alter table if exists round 
       add constraint FKppxonwn9e98lccy46m2eve67m 
       foreign key (game_id) 
       references game;

    alter table if exists round 
       add constraint FKbrt4f1cewnfqflvqf96h5g81j 
       foreign key (president_id) 
       references player;

    alter table if exists round_available_laws 
       add constraint FKql4fgg2jr9u4smdax3nkjl5e1 
       foreign key (law_id) 
       references law;

    alter table if exists round_available_laws 
       add constraint FK82ps36li4w1no5vl3crd0l8im 
       foreign key (round_id) 
       references round;

    alter table if exists round_votes 
       add constraint FKj5skl2so858mvt1rgejspo52f 
       foreign key (player_id) 
       references player;

    alter table if exists round_votes 
       add constraint FKtc8na4gfdpm8jsyyv1bkt80wx 
       foreign key (round_id) 
       references round;

    alter table if exists tag 
       add constraint FKfths0gjayk5sgph0wmt26xmqr 
       foreign key (lang_id) 
       references lang;

    alter table if exists telegram_game 
       add constraint FK6pnautggosoc7dd8iki7m0s9x 
       foreign key (game_id) 
       references game;

    alter table if exists telegram_player 
       add constraint FKommegdf9a3u5wc3md30b2hgix 
       foreign key (player_id) 
       references player;

    alter table if exists telegram_room 
       add constraint FKp9i88sufkoffr3dskuslsljl2 
       foreign key (room_id) 
       references room;

    alter table if exists telegram_user 
       add constraint FK4fpwstgmikyoruwr0t96q434r 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FK5tj0aisj3e9c62bc75fy2he87 
       foreign key (lang_id) 
       references lang;
